[project]
name = "image_generation_pytorch"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pavel Zwerschke <pavelzw@gmail.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64"]

[system-requirements]
linux = "4.18.0"

[tasks]
lint = "ruff ."
format = "black ."

[dependencies]
python = "3.10.*"
pytorch = "1.13.*"
torchvision = "0.14.*"
scipy = "1.11.*"
tensorflow = "2.12.*"
imageio = "2.31.1.*"
tqdm = "4.66.1.*"
loguru = "0.7.2.*"
ruff = "*"
black = "*"
opt_einsum = ">=3.3.0"
opt-einsum = ">=3.3.0"
